trigger:
- react-multi-stage

resources:
- repo: self
pool: NH-Pool

variables:

 # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd9b5dc97-9517-4cc6-945e-7563c7a082f2'
  imageRepository: 'react-app'
  containerRegistry: 'nodebaseimage.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      NH-Pool
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
        
    # - task: CmdLine@2
    #   inputs:
    #     script: |
    #       echo $(Build.BuildId) > $(Pipeline.Workspace)/imageTag.txt
    #     displayName: 'Save image tag'
    # - task: PublishPipelineArtifact@1
    #   inputs:
    #     targetPath: '$(Pipeline.Workspace)/imageTag.txt'
    #     artifact: 'imageTag'
    #     publishLocation: 'pipeline'
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'


##################################################################################
# - stage: Deploy
#   displayName: Deploy stage
#   dependsOn: Build
#   jobs:
#   - job: Deploy
#     displayName: Deploy
#     pool:
#       NH-Pool
#     steps: 
#           - task: KubernetesManifest@0
#             displayName: Deploy to Kubernetes cluster
#             inputs:
#               action: 'deploy'
#               # connectionType: 'kubernetesServiceConnection'
#               kubernetesServiceConnection: 'Test-default'
#               namespace: 'default'
#               manifests: 'manifests/*.yml'
#               containers: '$(containerRegistry)/$(imageRepository):$(tag)' 
            

