---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: reactapp 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp 
    spec:
      containers:
        - name: reactapp 
          image: nodebaseimage.azurecr.io/react-app:#{Build.BuildId}#
          imagePullPolicy: Always
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: reactapp
spec:
    type: ClusterIP
    ports:
    - port: 80 
    selector:
        app: reactapp          